//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.04.16 at 12:51:42 PM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://roast.io", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package io.roast;
